##Tail
prebuild:

debug:

qrun:
	rm -rf ./build && mkdir build
	cd build && cmake .. && make && ./ice_web_demo
test:

install:

clean:

build:
	rm -rf ./build && mkdir build
	cd build && cmake .. && make


